import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';
import ReactQueryProvider from '@/providers/react-query';

export const metadata: Metadata = {
  title: {
    template: '%s | Jira Clone',
    default: 'Jira Clone',
  },
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ReactQueryProvider>
        <body className={cn('antialiased min-h-screen', inter.className)}>{children}</body>
      </ReactQueryProvider>
    </html>
  );
}
