import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';
import ReactQueryProvider from '@/providers/react-query';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: {
    template: '%s | Jira Clone',
    default: 'Jira Clone',
  },
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang='en'>
        <body className={cn('antialiased min-h-screen', inter.className)}>{children}</body>
        <Toaster />
      </html>
    </ReactQueryProvider>
  );
}
